### ISSUE TITLE
Simple toolbar broken in Chrome

### ISSUE THREAD

**Issue by addyosmani** [jquery-ui-bootstrap/jquery-ui-bootstrap#128]
As per http://cl.ly/image/1q2m0Q413m1o

This doesn't appear to be an issue caused by the width of the container.

**Comment by addyosmani** [comment]
@gtraxx are you able to confirm?

**Comment by gtraxx** [comment]
@addyosmani This is a problem with inheritance bootstrap.css, I'm looking for how to fix chrome

:)

**Comment by gtraxx** [comment]
Hi @addyosmani, I found a solution to the problem of positioning toolbar in chrome.
A inheritance from bootstrap.css displays the problem, only a hack solution.

I do not like hacks but you would be an alternative

Here is my solution:

``` css
#toolbar {
    padding: 5px 0 5px 5px;
}
/*
* Bug chrome with toolbar and bootstrap inheritance
*/
@media screen and (-webkit-min-device-pixel-ratio:0) {
    #toolbar input{display:block;float:left;}
}
```

Is what I publish?
