### ISSUE TITLE
CSS - Simple tabs - border-bottom

### ISSUE THREAD

**Issue by sire-sam** [jquery-ui-bootstrap/jquery-ui-bootstrap#136]
@gtraxx 

On simple tabs display (http://addyosmani.github.com/jquery-ui-bootstrap/index.html#tabs-simple) a border is visible at the bottom of an active item, but should be hidden (following original bootstrap)

Could be fix by adding 

``` CSS
    margin-bottom: -1px;
```

On the following declaration 

``` CSS
.ui-tabs .ui-tabs-nav li {
    filter: none;
 }
```
