### ISSUE TITLE
Click/focus on <input type="button">  button produces undesirable rendering

### ISSUE THREAD

**Issue by cdaringe** [jquery-ui-bootstrap/jquery-ui-bootstrap#258]
With no other resources on a page except for jquery-ui-bootstrap css, in google chrome, clicking an `<input type="button">` drastically changes the buttons appearance.  Tested with and without the .css to confirm.

![screen shot 2014-11-14 at 5 46 48 pm](https://cloud.githubusercontent.com/assets/1003261/5056098/b212b0bc-6c26-11e4-8557-2aaa0b1e4710.png)

**Comment by cdaringe** [comment]
The css checks out as valid css3, however, the only property that doesn't seem to impact the rendering after click events is `outline: 0;`.  This appears to feasibly be a browser bug.  Will someone else confirm that this behavior is observed?  ~ Line 2261

``` css
input:focus, textarea:focus {
  outline: 0;
  border-color: rgba(82, 168, 236, 0.8);
  -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1), 0 0 8px rgba(82, 168, 236, 0.6);
  -moz-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1), 0 0 8px rgba(82, 168, 236, 0.6);
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1), 0 0 8px rgba(82, 168, 236, 0.6);
}
```
