### ISSUE TITLE
Positioning for jquery-ui button icons

### ISSUE THREAD

**Issue by SystemParadox** [jquery-ui-bootstrap/jquery-ui-bootstrap#57]
Hi. I'm in the process of switching over an existing jquery-ui app. I found that jquery-ui-bootstrap doesn't position button icons correctly (they end up in the top left, with the text underneath). Some of the components used can't easily be changed to do it 'the bootstrap way', so I came up with the following CSS to position them correctly.

Maybe this could be included in jquery-ui-bootstrap? This shouldn't break buttons done 'the bootstrap way' due to the use of the 'ui-button-text-icon-primary' class.

``` css
.ui-button-text-icon-primary {
    position: relative;
}
.ui-button-text-icon-primary .ui-icon {
    position: absolute;
    top: 50%;
    margin-top: -8px;
}
```

**Comment by addyosmani** [comment]
@SystemParadox Agreed. I'm hoping to fix this as a part of the rewrite to upgrade to Bootstrap 2.0. Will keep open as a reminder.

**Comment by SystemParadox** [comment]
Sounds good to me. Really looking forward to the bootstrap 2.0 version.
Many thanks.

**Comment by SystemParadox** [comment]
Fixes for icon-only buttons:

``` css
button.ui-button-icon-only {
    position: relative;
    padding: 0;
    min-height: 24px; /* http://bugs.jqueryui.com/ticket/5603 */
    width: 24px;
}
button.ui-button-icon-only .ui-icon {
    position: absolute;
    top: 50%;
    margin-top: -8px;
    left: 50%;
    margin-left: -8px;
}
```

Caution: Firefox has problems with absolute positioning and padding in buttons. Still broken in 7, works in 10 (don't know about 8 or 9). Consider avoiding padding on the button element itself. See: https://bugzilla.mozilla.org/show_bug.cgi?id=437722
